#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_DIR=$SCRIPT_DIR"/config"

#if [[ "$XGD_CURRENT_DESKTOP" -eq "i3" ]]; then SCRIPT_DIR=$SCRIPT_DIR"_i3"; fi

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch bar1 and bar2

polybar --config=$SCRIPT_DIR bar &

echo "Bars launched..."
